name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.1.1
homepage: https://github.com/donjordano/bitcoin_flutter
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bip39: ^1.0.6
  bip32: ^2.0.0
  pointycastle: ^3.6.0
  hex: ^0.2.0
  bs58check: ^1.0.2
  bech32:
    git: https://github.com/donjordano/bech32.git
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.21.1

dependency_overrides:
  analyzer: 5.3.1
  convert: ^3.1.1
  crypto: ^3.0.2
  hex: ^0.2.0
